use_frameworks!

platform :ios, '8.0'

target 'LSTCategory_Example' do
  pod 'LSTCategory', :path => '../'
#  pod 'YYModel'
#  pod 'YYWebImage'

  target 'LSTCategory_Tests' do
    inherit! :search_paths

    
  end
end
